github.com:
    users:
        kishorekannann:
            oauth_token: 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
    git_protocol: https
    user: kishorekannann
    oauth_token: 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
